create table public.bat_completed_auctions (
  id serial not null,
  listing_id text not null,
  url text not null,
  title text not null,
  image_url text null,
  sold_price integer null,
  sold_date timestamp without time zone null,
  bid_amount integer null,
  bid_date timestamp without time zone null,
  status text null,
  year integer null,
  make text null,
  model text null,
  source_file text null,
  created_at timestamp without time zone null default now(),
  updated_at timestamp without time zone null default now(),
  mileage integer null,
  bidders integer null,
  watchers integer null,
  comments integer null,
  transmission text null,
  constraint bat_completed_auctions_pkey primary key (id),
  constraint bat_completed_auctions_listing_id_key unique (listing_id)
) TABLESPACE pg_default;